# Generated by Django 2.1.3 on 2018-11-06 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=50)),
                ('contrasenha', models.CharField(max_length=20)),
                ('tipoAdministrador', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.PositiveIntegerField()),
                ('columna', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numeroPasaporte', models.CharField(max_length=50, verbose_name='Numero de Pasaporte')),
                ('paisProcedencia', models.CharField(max_length=50, verbose_name='Pais de Procedencia')),
                ('correo', models.EmailField(max_length=50)),
                ('contrasenha', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteXVuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=20)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volasa.Asiento')),
            ],
        ),
        migrations.CreateModel(
            name='EquipajeRegistrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoVuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoAvion', models.CharField(max_length=20)),
                ('cantidadAsientos', models.PositiveIntegerField()),
                ('aerolinea', models.CharField(max_length=50)),
                ('fechaPartida', models.DateTimeField()),
                ('fechaLlegada', models.DateTimeField()),
                ('precio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cantidadEscalas', models.PositiveIntegerField()),
                ('cliente', models.ManyToManyField(through='volasa.ClienteXVuelo', to='volasa.Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='clientexvuelo',
            name='equipaje',
            field=models.ManyToManyField(to='volasa.EquipajeRegistrado'),
        ),
        migrations.AddField(
            model_name='clientexvuelo',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volasa.Cliente'),
        ),
        migrations.AddField(
            model_name='clientexvuelo',
            name='idEstadoVuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volasa.EstadoVuelo'),
        ),
        migrations.AddField(
            model_name='clientexvuelo',
            name='idVuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volasa.Vuelo'),
        ),
    ]
